# Nombre del servicio
spring.application.name=bff-service

# Puerto oficial de entrada para el Frontend
server.port=8080

# URLs de los microservicios internos a los que llamará el BFF
microservice.incident.url=http://localhost:8081