# Nombre del servicio
spring.application.name=bff-service

# Puerto oficial de entrada para el Frontend
server.port=8080

# URLs de los microservicios internos a los que llamará el BFF
# Apunta al nombre del contenedor del microservicio de incidentes
microservice.incident.url=http://incident-service:8081