# Nombre del servicio
spring.application.name=bff-service

# Puerto oficial de entrada para el Frontend
server.port=8080

# URLs de los microservicios internos a los que llamará el BFF
# Apunta al nombre del contenedor del microservicio de incidentes
microservice.incident.url=http://incident-service:8081
microservice.geo.url=http://geo-service:8083

# RabbitMQ — broker de resiliencia para reportes
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest