# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.port=8083
spring.application.name=geo-service

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL)
# ==========================================
# Apunta al contenedor "postgres-db" y usa variable para la clave
spring.datasource.url=jdbc:postgresql://postgres-db:5432/geo_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:232312}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN DE RABBITMQ (Docker)
# ==========================================
# Apunta al contenedor de RabbitMQ en Docker
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ==========================================
# CONFIGURACIÓN SEGURIDAD Y JWT
# ==========================================
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000