spring.application.name=incident-service

server.port=8081

# Apunta al contenedor de MongoDB en Docker
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=incidentdb

# Apunta al contenedor de RabbitMQ en Docker
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest